language: node_js
node_js:
- '5'
notifications:
  slack:
    secure: hPtlYjrJh5IUIGX/kO+9vVGa1NFBDOV3Mx9zfNEjLss177rj5t+9HXQaWyL/0/Cai6f3qqH4KZdPHJAj8G6dBHWcEIXwDkTy59IYV8jnewhTZpptmUFPQK8c3k5BC++PUEbkApLk8WSRkebdSoW7pHsduFdYtZbo2CP0IAdGpv/5WRR4ncPwI2IKBFHv7lX6Owi0tjiO5qRjFlaMjHW3ooe2hZxQlA6wR9WSclFAeIE2FPr/ZZKdPC0rxSk5qZV30ehF7f1cCQumy0Az22ErGdpcj8M4weu7xeTK8YqMMiS2DmWhOJUxmXBWvhBCHxDLF58ipmchvgD4ukztxYHqkXPMZxgJ7P0663pnu4dKgfO7qMRnB+JkQHmqyleWWvGtU2jY0sEnN+tmgGdN/XxCcHyNJ9G/Bdevmf5T6diFesoxsQ4KNdpc25VoDHUs1wG7Btc/0RiftsBL8mtiTGc4Nohpq0xUYzDEdyP713PWiyOJIbM8UZqy2vJWSl+7RPxfTtelbqRaYt11rn7epF9rz1cVWbiRYBeqcF3+jlf9/WIzVxhG/39lSQEFX2/XycnPZtoKbmAO9/2F7L3LAVN+1x/+AF0/4q4lRd7w8WAZOV2T74ja6tqtErH/GSOiFwFSa3g1gkcR4u6Url93K4heQLUQG1XHMz5nnVN6beyi940=
